name: CI/CD FastAPI on Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/fastapi-k8s-cicd:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

#      - name: Deploy to AKS
 #       run: |
  #        kubectl apply -f k8s/deployment.yaml
   #       kubectl apply -f k8s/service.yaml

